version: '3.9'

services:
  pumpfun-bot:
    build: .
    container_name: pumpfun-bot
    restart: always
    # Если используешь переменные окружения через dockhost — раскомментируй:
    # env_file:
    #   - .env
